"use client";

import { useState, useEffect, Suspense, useMemo } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { PageContainer } from "@/components/layout/PageContainer";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { UploadTestBatch } from "@/components/analysis/UploadTestBatch";
import { PromptInput } from "@/components/analysis/PromptInput";
import { DuplicateProjectNameError } from "@/lib/db/projects";
import { useFullAnalysisPipeline } from "@/lib/hooks/useFullAnalysisPipeline";
import type { TestResult } from "@/types";
import { useToast } from "@/hooks/use-toast";
import { BackButton } from "@/components/layout/BackButton";
import { Loader2 } from "lucide-react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { useProjects } from "@/lib/hooks/useProjects";
import { useFolders } from "@/lib/hooks/useFolders";

function NewIterationPageInner() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const folderId = searchParams.get("folderId");

  const [projectName, setProjectName] = useState("");
  const [systemPrompt, setSystemPrompt] = useState("");
  const [promptSource, setPromptSource] = useState<"scratch" | "continue">("scratch");
  const [selectedIteration, setSelectedIteration] = useState<string | null>(null);
  const [uploadedTests, setUploadedTests] = useState<{
    tests: TestResult[];
    fileName: string;
    fileType: "json" | "csv" | "excel";
  } | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const { toast } = useToast();

  // Get existing iterations (projects) in this folder/prompt
  const { projectsWithStatus, loading: projectsLoading } = useProjects({ includeStatus: true });
  const { folders, loading: foldersLoading } = useFolders();

  const existingIterations = useMemo(() =>
    folderId
      ? projectsWithStatus.filter(p => p.folderId === folderId).sort((a, b) =>
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        )
      : [],
    [folderId, projectsWithStatus]
  );

  const currentFolder = folderId ? folders.find(f => f.id === folderId) : null;

  const { progress, runPipeline, isRunning } = useFullAnalysisPipeline();

  // Track if we've auto-generated a name (to avoid overwriting user input)
  const [hasAutoGeneratedName, setHasAutoGeneratedName] = useState(false);
  const dataLoaded = !projectsLoading && !foldersLoading;

  // Auto-generate iteration name based on folder name and existing iterations
  // Only run once when data is fully loaded
  useEffect(() => {
    if (dataLoaded && folderId && currentFolder && !hasAutoGeneratedName) {
      const nextNumber = existingIterations.length + 1;
      setProjectName(`${currentFolder.name} ${nextNumber}`);
      setHasAutoGeneratedName(true);
    }
  }, [dataLoaded, folderId, currentFolder, existingIterations.length, hasAutoGeneratedName]);

  // Load prompt from selected iteration
  useEffect(() => {
    if (promptSource === "continue" && selectedIteration) {
      const iteration = existingIterations.find(p => p.id === selectedIteration);
      if (iteration) {
        setSystemPrompt(iteration.systemPrompt || "");
      }
    } else if (promptSource === "scratch") {
      setSystemPrompt("");
    }
  }, [promptSource, selectedIteration, existingIterations]);

  const handleUpload = (
    tests: TestResult[],
    fileName: string,
    fileType: "json" | "csv" | "excel"
  ) => {
    setUploadedTests({ tests, fileName, fileType });
  };

  const handleCreate = async () => {
    const nextErrors: Record<string, string> = {};
    if (!projectName.trim()) {
      nextErrors.name = "Project name is required.";
    }
    if (!systemPrompt.trim()) {
      nextErrors.prompt = "System prompt is required.";
    }
    if (!uploadedTests) {
      nextErrors.tests = "Please upload a test batch.";
    }
    setErrors(nextErrors);
    if (Object.keys(nextErrors).length > 0) return;

    try {
      const result = await runPipeline({
        projectName: projectName.trim(),
        systemPrompt: systemPrompt.trim(),
        tests: uploadedTests!.tests,
        fileName: uploadedTests!.fileName,
        fileType: uploadedTests!.fileType,
        folderId: folderId || undefined,
      });

      if (!result.success) {
        toast({
          title: "Analysis failed",
          description: result.error || "Please try again.",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error("Failed to create project:", error);
      if (error instanceof DuplicateProjectNameError) {
        setErrors((prev) => ({
          ...prev,
          name: `${error.message} Try "${error.suggestedName}" instead.`,
        }));
      } else {
        toast({
          title: "Failed to create project",
          description: "Please try again.",
          variant: "destructive",
        });
      }
    }
  };

  const canCreate = projectName.trim() && systemPrompt.trim() && uploadedTests;

  const getProgressMessage = () => {
    if (progress.step === "generating" && progress.currentCategory && progress.totalCategories) {
      return `${progress.message} (${progress.currentCategory}/${progress.totalCategories})`;
    }
    return progress.message;
  };

  return (
    <PageContainer>
      <div className="mx-auto max-w-3xl space-y-8">
        <div className="mb-6 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <BackButton
              href={folderId ? `/dashboard?folder=${folderId}` : "/dashboard"}
              label={folderId ? `Back to ${currentFolder?.name || "prompt"}` : "Back to dashboard"}
            />
            <div>
              <h1 className="text-3xl font-bold text-gray-900">New Iteration</h1>
              <p className="mt-2 text-gray-600">
                {currentFolder
                  ? `Create a new iteration for "${currentFolder.name}"`
                  : "Upload your test batch and system prompt to get started"
                }
              </p>
            </div>
          </div>
        </div>

        <Card className="p-6 transition-smooth">
          <div className="space-y-6">
            <div className="space-y-2" data-tour="iteration-name">
              <Label htmlFor="project-name" className="text-base font-semibold">
                Iteration Name
              </Label>
              <Input
                id="project-name"
                value={projectName}
                onChange={(e) => {
                  setProjectName(e.target.value);
                  if (errors.name) {
                    setErrors((prev) => {
                      const { name, ...rest } = prev;
                      return rest;
                    });
                  }
                }}
                placeholder="e.g., Iteration 1"
                className={errors.name ? "border-red-500" : ""}
                aria-invalid={!!errors.name}
                aria-describedby={errors.name ? "project-name-error" : undefined}
                disabled={isRunning}
              />
              {errors.name && (
                <p id="project-name-error" className="text-sm text-red-600">
                  {errors.name}
                </p>
              )}
            </div>

            <div data-tour="test-batch-upload">
              <h3 className="mb-4 text-base font-semibold">Upload Test Batch</h3>
              <UploadTestBatch
                onUpload={(tests, fileName, fileType) => {
                  handleUpload(tests, fileName, fileType);
                  if (errors.tests) {
                    setErrors((prev) => {
                      const { tests: _, ...rest } = prev;
                      return rest;
                    });
                  }
                }}
                disabled={isRunning}
              />
              {errors.tests && (
                <p className="mt-2 text-sm text-red-600">{errors.tests}</p>
              )}
            </div>

            {/* Prompt Source Selection - only show if there are existing iterations */}
            {existingIterations.length > 0 && (
              <div className="space-y-4">
                <Label className="text-base font-semibold">System Prompt Source</Label>
                <RadioGroup
                  value={promptSource}
                  onValueChange={(value: "scratch" | "continue") => {
                    setPromptSource(value);
                    if (value === "scratch") {
                      setSelectedIteration(null);
                    }
                  }}
                  disabled={isRunning}
                >
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="scratch" id="scratch" />
                    <Label htmlFor="scratch" className="font-normal cursor-pointer">
                      Start from scratch
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="continue" id="continue" />
                    <Label htmlFor="continue" className="font-normal cursor-pointer">
                      Continue from previous iteration
                    </Label>
                  </div>
                </RadioGroup>

                {promptSource === "continue" && (
                  <div className="ml-6 space-y-2">
                    <Label htmlFor="iteration-select" className="text-sm text-gray-600">
                      Select iteration to continue from:
                    </Label>
                    <select
                      id="iteration-select"
                      value={selectedIteration || ""}
                      onChange={(e) => setSelectedIteration(e.target.value || null)}
                      className="w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                      disabled={isRunning}
                    >
                      <option value="">Select an iteration...</option>
                      {existingIterations.map((iteration, index) => (
                        <option key={iteration.id} value={iteration.id}>
                          {iteration.name} (created {new Date(iteration.createdAt).toLocaleDateString()})
                        </option>
                      ))}
                    </select>
                  </div>
                )}
              </div>
            )}

            <div data-tour="system-prompt">
            <PromptInput
              value={systemPrompt}
              onChange={(value) => {
                setSystemPrompt(value);
                if (errors.prompt) {
                  setErrors((prev) => {
                    const { prompt, ...rest } = prev;
                    return rest;
                  });
                }
              }}
              disabled={isRunning || (promptSource === "continue" && !selectedIteration)}
            />
            </div>
            {errors.prompt && (
              <p className="text-sm text-red-600">{errors.prompt}</p>
            )}
          </div>
        </Card>

        {/* Progress indicator */}
        {isRunning && (
          <Card className="p-4 transition-smooth">
            <div className="flex items-center gap-3">
              <Loader2 className="h-5 w-5 animate-spin text-blue-500" />
              <div className="flex-1">
                <p className="font-medium text-gray-900">{getProgressMessage()}</p>
                <div className="mt-2 h-2 w-full overflow-hidden rounded-full bg-gray-200">
                  <div
                    className="h-full bg-blue-500 transition-all duration-500"
                    style={{
                      width: progress.step === "creating" ? "10%" :
                             progress.step === "analyzing" ? "30%" :
                             progress.step === "generating" && progress.currentCategory && progress.totalCategories
                               ? `${30 + (progress.currentCategory / progress.totalCategories) * 60}%`
                               : progress.step === "complete" ? "100%" : "0%"
                    }}
                  />
                </div>
              </div>
            </div>
          </Card>
        )}

        {progress.step === "error" && (
          <Card className="border-red-200 bg-red-50 p-4 transition-smooth">
            <p className="text-sm text-red-900">{progress.error}</p>
          </Card>
        )}

        <div className="flex justify-end gap-4">
          <Button
            variant="outline"
            onClick={() => router.push("/dashboard")}
            disabled={isRunning}
          >
            Cancel
          </Button>
          <Button onClick={handleCreate} disabled={!canCreate || isRunning} data-tour="create-analyze">
            {isRunning ? "Processing..." : "Create & Analyze"}
          </Button>
        </div>
      </div>
    </PageContainer>
  );
}

export default function NewIterationPage() {
  return (
    <Suspense fallback={
      <PageContainer>
        <div className="mx-auto max-w-3xl space-y-8">
          <div className="animate-pulse">
            <div className="h-8 bg-gray-200 rounded w-1/4 mb-4"></div>
            <div className="h-4 bg-gray-200 rounded w-1/2"></div>
          </div>
        </div>
      </PageContainer>
    }>
      <NewIterationPageInner />
    </Suspense>
  );
}
